media:
  input: public/
  output: /
content:
  - name: posts
    label: Posts
    type: collection
    path: src/content/blog
    fields:
      - name: title
        type: string
      - name: pubDate
        type: date
        options:
          format: "yyyy-MM-dd"
      - name: published
        type: boolean
        default: false
      - name: description
        type: string
      - name: body
        type: rich-text
settings:
  content:
    merge: true
  commit:
    identity: app
    templates:
      create: "content(create): {path}"
      update: "content(update): {path}"
      delete: "content(delete): {path}"
      rename: "content(rename): {oldPath} -> {newPath}"
