media:
  input: public/
  output: /
content:
  - name: posts
    label: Posts
    type: collection
    path: src/content/blog
    fields:
      - name: title
        type: string
      - name: pubDate
        type: date
        options:
          format: "yyyy-MM-dd"
      - name: published
        type: boolean
        default: false
      - name: description
        type: string
      - name: body
        type: rich-text
    view:
      fields: [title, pubDate, published]
      sort: [pubDate, title]
      default:
        sort: pubDate
        order: desc
  - name: sidebars
    label: Sidebars
    type: group
    items:
      - name: left
        type: file
        path: src/content/sidebar-left.md
      - name: right
        type: file
        path: src/content/sidebar-right.md
settings:
  content:
    merge: true
  commit:
    identity: app
    templates:
      create: "chore(create): {path}"
      update: "chore(update): {path}"
      delete: "chore(delete): {path}"
      rename: "chore(rename): {oldPath} -> {newPath}"
