media:
  - name: images
    input: src/assets/images/content
    output: "@assets/images/content"
    rename: safe
content:
  - name: about
    label: À propos
    type: file
    path: src/content/about.md
    fields:
      - name: title
        type: string
      - name: body
        type: rich-text
  - name: posts
    label: Blog
    type: collection
    path: src/content/blog
    fields:
      - name: title
        type: string
      - name: pubDate
        type: date
        options:
          format: "yyyy-MM-dd"
      - name: published
        type: boolean
        default: true
      - name: description
        type: string
      - name: tags
        type: string
        list: true
      - name: body
        type: rich-text
    view:
      fields: [title, pubDate, published]
      sort: [pubDate, title]
      default:
        sort: pubDate
        order: desc
  - name: reviews
    label: Music
    type: collection
    path: src/content/reviews
    fields:
      - name: title
        type: string
      - name: pubDate
        type: date
        options:
          format: "yyyy-MM-dd"
      - name: published
        type: boolean
        default: true
      - name: artist
        type: string
      - name: cover
        type: image
        options:
          media: images
      - name: description
        type: string
      - name: tags
        type: string
        list: true
      - name: body
        type: rich-text
    view:
      fields: [title, pubDate, published]
      sort: [pubDate, title]
      default:
        sort: pubDate
        order: desc
settings:
  content:
    merge: true
  commit:
    identity: app
    templates:
      create: "chore(create): {path}"
      update: "chore(update): {path}"
      delete: "chore(delete): {path}"
      rename: "chore(rename): {oldPath} -> {newPath}"
